apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: neo4j
  name: neo4j
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - image: neo4j:4.2.1-enterprise
        name: neo4j
        env:
        - name: NEO4J_AUTH
          value: neo4j/neo@Home
        - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
          value: "yes"
        ports:
        - containerPort: 7474
          name: tcp-http
        - containerPort: 7687
          name: tcp-bolt
