apiVersion: v1
kind: Service
metadata:
  name: neo4j
  labels:
    app: neo4j
spec:
  type: LoadBalancer
  ports:
  - name: tcp-bolt
    port: 7687
    targetPort: 7687
  - name: tcp-http
    port: 80
    targetPort: 7474
  selector:
    app: neo4j
